name: Build kernel

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:

  schedule:
    - cron: '29 4 1,15 * *'
  push:
    branches:
      - force-build

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq --no-install-recommends \
                git bc bison flex libssl-dev make libc6-dev libncurses5-dev devscripts
          sudo apt-get install -yqq --no-install-recommends \
                crossbuild-essential-armhf crossbuild-essential-arm64

      - name: Build kernel
        id: build-kernel
        run: |
          ./build-kernel.sh --arch=arm64 --deb-arch=arm64 -jX

      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: nomad-kernel-${{ steps.build-kernel.outputs.package-version }}
          path: ${{ steps.build-kernel.outputs.deb-package }}
